<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper"/>
    <PackageReference Include="FluentValidation"/>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
    <PackageReference Include="Libwebp.Net"/>
    <PackageReference Include="Microsoft.AspNetCore.Http"/>
    <PackageReference Include="Microsoft.Extensions.Http"/>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions"/>
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens"/>
    <PackageReference Include="Riok.Mapperly"/>
    <PackageReference Include="SixLabors.ImageSharp"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inkukan.Domain\Inkukan.Domain.csproj" />
  </ItemGroup>

</Project>
